import subprocess
from pathlib import Path

import pytest

from fileconv.ffmpeg_utils import find_ffmpeg
from fileconv.video import convert_audio, convert_video


@pytest.fixture(scope="module")
def sample_mp4(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """1-second test video (color bars + sine tone) generated by ffmpeg."""
    path = tmp_path_factory.mktemp("media") / "sample.mp4"
    subprocess.run(
        [
            find_ffmpeg(), "-hide_banner", "-y",
            "-f", "lavfi", "-i", "testsrc=duration=1:size=320x240:rate=15",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest",
            str(path),
        ],
        check=True,
        capture_output=True,
    )
    return path


def test_mp4_to_mov_remux(sample_mp4: Path, tmp_path: Path):
    dest = convert_video(sample_mp4, tmp_path / "out.mov")
    assert dest.exists() and dest.stat().st_size > 0


def test_mp4_to_hevc(sample_mp4: Path, tmp_path: Path):
    dest = convert_video(sample_mp4, tmp_path / "out.mp4", codec="hevc")
    assert dest.exists() and dest.stat().st_size > 0


def test_mov_back_to_mp4_h264(sample_mp4: Path, tmp_path: Path):
    mov = convert_video(sample_mp4, tmp_path / "mid.mov")
    dest = convert_video(mov, tmp_path / "back.mp4", codec="h264")
    assert dest.exists() and dest.stat().st_size > 0


def test_extract_audio_to_mp3(sample_mp4: Path, tmp_path: Path):
    dest = convert_audio(sample_mp4, tmp_path / "audio.mp3")
    assert dest.exists() and dest.stat().st_size > 0


def test_video_to_gif(sample_mp4: Path, tmp_path: Path):
    dest = convert_video(sample_mp4, tmp_path / "anim.gif")
    assert dest.exists() and dest.stat().st_size > 0
